package:
  name: ros-noetic-cnpy
  version: 0.0.2
source:
  git_url: https://github.com/PeterMitrano/cnpy-release.git
  git_rev: release/noetic/cnpy/0.0.2-1
  folder: ros-noetic-cnpy/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 4
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
  host:
    - cmake
    - python
    - ros-distro-mutex 0.1 noetic
    - zlib
  run:
    - python
    - ros-distro-mutex 0.1 noetic
